name: PwdGetter
main: io.d0048.pwdGetter.PwdGetter
version: 1.0
description: A simple password getter
author: HXB
commands: 
    getpinfo:
        description: Get the information about a player
        usage: /<command> player
        permission: blockode.op
        permission-message: 不用试了，你没权限0.0[Access Denied]